### ISSUE TITLE
Nice to have: navigazione di tutti gli episodi

### ISSUE THREAD

**Issue by agofa** [pdonadeo/e-uscito-joypad#101]
Richiesta intercettata anche su Joycord
Un sezione o quel che è per fare browsing di tutti gli episodi e non solo gli ultimi 8

Gestiti a pagine (per esempio a gruppi di 8)

Che ne pensate @pdonadeo  e @MarcoJul ?

Riferimento #37

**Comment by pdonadeo** [comment]
Non è possibile, la pagina diventerebbe pesantissima da caricare. Si può aumentare un po' gli episodi, da 8 a... 12 o 16 magari, ma non molto di più.

Che ne pensi @MarcoJul?

**Comment by MarcoJul** [comment]
L'unica che mi viene in mente è l'infinite scroll, ovviamente però legata a una chiamata a ogni scroll (con conseguente modifica degli endpoint attuali). 

Nel caso, si può decidere se attivarla con il semplice scroll (quando arrivi a fondo pagina parte la chiamata) o con un pulsante "mostra altro" che aggiunge 6-8-10 episodi alla pagina

Escluderei la paginazione, non mi piace granché, ma se vogliamo possiamo pensare anche a quella.

**Comment by pdonadeo** [comment]
Dico la mia: paginazione "1 2 3" no perché sa di vecchio. Infinite scroll è roba da social, negli altri siti del mondo è una schifezza e difatti non la si vede da nessuna parte (social a parte, ovviamente).

Invece lo "show more" mi piace.

Fare un nuovo endpoint ci metto poco, dimmi tu se ci vuoi lavorare, a questo punto.

**Comment by agofa** [comment]
Paginazione non sa di vecchio. É vecchio. Ma piuttosto che niente...

Sul resto sono d'accordo su tutta la linea, quale che sia. Voi fate e io testerò...

**Comment by MarcoJul** [comment]
@pdonadeo direi che mi ci posso mettere, il periodo de fuego dovrebbe essere passato.. Mi sembra una funzionalità di buona portata per poter riprendere😉

**Comment by pdonadeo** [comment]
Direi che questa è fatta.
