### ISSUE TITLE
Campo "Note" nella scheda "episodio"

### ISSUE THREAD

**Issue by agofa** [pdonadeo/e-uscito-joypad#19]
Credo sia utile un campo "note libere" nella scheda episodio
Per esempio nell'episodio 3 viene citato un gioco, Sky (dal creatore di Journey) che non riesco a trovare in rawg
Sarebbe utile poter annotare il problema per dare modo ad altri di fare la ricerca

**Comment by pdonadeo** [comment]
@agofa La modifica è online in questo momento.

**Comment by n1k9** [comment]
@pdonadeo la velocità della luce è un concetto relativo per te! :)
