### ISSUE TITLE
Parola che sembra un link ma non è un link

### ISSUE THREAD

**Issue by agofa** [pdonadeo/e-uscito-joypad#2]
Pavlov sarebbe orgoglioso di me.

Nella frase "È uscito <n> *l'episodio* ..." , quel "episodio" sottolineato mi ha fatto cliccare millemila volte 

Vabbé ....

**Comment by pdonadeo** [comment]
Credo sia un problema di chiarezza: i link nella pagina sono sottolineati e non dovrebbero.

**Comment by pdonadeo** [comment]
@agofa ho chiesto ad una persona capace di riguardare tutta la "grafica".

**Comment by agofa** [comment]
"Troppa grazia ... " :-)
