### ISSUE TITLE
Attuale sito

### ISSUE THREAD

**Issue by agofa** [pdonadeo/e-uscito-joypad#20]
C'entra un piffero con questo sviluppo, quindi se ritenete, bruciate pure la issue
Il fatto è che essendo uscito su Twitch e essendo che la pagina del post non è aggiornata, il sito attuale non si è ancora accorto che la puntat, l'episod, l'even ... insomma quel coso lì è uscito.

**Comment by pdonadeo** [comment]
Se ne accorgerà quando verrà pubblicato ufficialmente sul Post.

**Comment by agofa** [comment]
Severo ma giusto.
