### ISSUE TITLE
Inserire info su segnalazioni non relative a giochi

### ISSUE THREAD

**Issue by agofa** [pdonadeo/e-uscito-joypad#24]
Per esempio, ep 11, al minuto 40:00 Zampa consiglia un libro e non un gioco, Sega Arcade Pop-up History (Read Only Memory), che non c'è modo di inserire

**Comment by pdonadeo** [comment]
Direi che questa la considero davvero troppo: non possiamo inserire qualsiasi cosa altrimenti non ne usciamo vivi.

Quindi per me i libri... andranno dimenticati, mi spiace.
