### ISSUE TITLE
Errore di certificato 

### ISSUE THREAD

**Issue by n1k9** [pdonadeo/e-uscito-joypad#34]
I siti web garantiscono la propria identità attraverso certificati. Firefox non considera questo sito attendibile in quanto utilizza un certificato che non è valido per www.euscitojoypad.it. Il certificato è valido solo per data-collector-2.4sigma.it.
 
Codice di errore: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by pdonadeo** [comment]
Ma Nicola… cosa non era chiaro in "fermo per manutenzione straordinaria?" 😉 

Vedi: https://github.com/pdonadeo/e-uscito-joypad/discussions/33#discussioncomment-3111914

**Comment by n1k9** [comment]
Poteva benissimo essere una conseguenza dellla manutenzione, non ho segnalato il down della macchina ma il dominio errato nel certificato!
