### ISSUE TITLE
Episodi invertiti in staging

### ISSUE THREAD

**Issue by agofa** [pdonadeo/e-uscito-joypad#35]
Il video 2, quindi il secondo degli epicosi, è diviso in due parti.
Nell'elenco che si vede in staging la seconda parte viene prima della prima (e vabbé)

![Screenshot_20220717-113430_Chrome.jpg](https://user-images.githubusercontent.com/19308040/179392533-3d657d19-e928-47b3-a6de-8221fd6da76c.jpg)

**Comment by MarcoJul** [comment]
Ok, vedo se posso girarli in front o se è meglio scriverli in altro modo direttamente nel database🖖

**Comment by pdonadeo** [comment]
@agofa questa issue si è risolta "da sola", almeno credo, visti gli ultimi cambiamenti. La chiudo. Se mi sbaglio riaprila pure.
