### ISSUE TITLE
Non si vedono tutti gli episodi

### ISSUE THREAD

**Issue by agofa** [pdonadeo/e-uscito-joypad#37]
Forse c'è una paginazione che mi sta sfuggendo, però vedo solo gli episodi dal 53 al 47
Provati FF e Edge su desktop, Firefox e Duck su cellulino (c)

@pdonadeo boh?

**Comment by pdonadeo** [comment]
Non c'è paginazione, ho lasciato solo alcuni episodi perché metterli tutti rende la pagina lentissima. Essendo un campo di ricerca quella lista è il risultato della ricerca. Forse potremmo toglierla del tutto a questo punto, non so che dite?

**Comment by agofa** [comment]
Non ho capito, però
Appena si entra in home si vedono gli ultimi 7 episodi?
Se è così, basterebbe forse solo scriverlo in modo che sia chiaro
Ma forse non ho capito

**Comment by pdonadeo** [comment]
@agofa non so bene cosa fare — cosa vogliamo fare — con quella lista ma so quello che non ha senso fare: caricare una lista di 86 episodi e 86 immagini.

C'è da riflettere un po': se non è chiaro cosa sta succedendo, come dici, allora penso che possiamo eliminare la lista iniziale e far apparire qualcosa solo quando si fa una ricerca.

**Comment by agofa** [comment]
> caricare una lista di 86 episodi e 86 immagini.

D'accordo al 100%

Ma quindi si potrebbero mostrare solo gli ultimi "n" episodi, tipo vetrina, spiegandolo nella pagina
Oppure come dici tu
Mostrarne alcuni senza dare spiegazioni, secondo me, mette fuori strada

**Comment by MarcoJul** [comment]
Propongo per integrare (più avanti) la paginazione, che però significherebbe strutturare il backend in modo che al cambio pagina possa partire una richiesta separata delle puntate coinvolte. Magari segnamolo come integrazione per eventuale fase 2😉

**Comment by pdonadeo** [comment]
> Propongo per integrare (più avanti) la paginazione, che però significherebbe strutturare il backend in modo che al cambio pagina possa partire una richiesta separata delle puntate coinvolte. Magari segnamolo come integrazione per eventuale fase 2wink

Concordo: Marco sappi che se ci sarà una fase 2, come spero, teniamo tutto il frontend ma la comunicazione col server sarà da rifare, e non solo per la paginazione. Ma questo penso che tu già lo sappia 😄

Pensi di voler ancora lavorare al progetto?

**Comment by MarcoJul** [comment]
Senza problemi, se mi volete ancora sono qui, fra l'altro anche se non magari lato UI, sottotraccia il codice andrà pulito molto (oltre a finire i punti ancora pending).

Ovviamente interpellerò di nuovo Chiara per eventuali sistemazioni e integrazioni diverse, se mi metto di mia iniziativa finisco per snaturare tutto il progetto😅

**Comment by pdonadeo** [comment]
@agofa Ma questa issue è un duplicato di #101? La possiamo chiudere?

**Comment by agofa** [comment]
Uh sì sì ero convinto di averlo scritto, e forse le ho collegate
Chiudi pure
