### ISSUE TITLE
Tastiera nasconde barra ricerca su FIREFOX e ANDROID

### ISSUE THREAD

**Issue by agofa** [pdonadeo/e-uscito-joypad#38]
Su mobile la tastiera nasconde la barra della ricerca mentre si sta scrivendo **PARE SOLO SU FIREFOX PERO'**
![immagine](https://user-images.githubusercontent.com/19308040/181917612-e3cbc972-1e3f-44c2-afd2-282a4ae77281.png)

_Originally posted by @agofa in https://github.com/pdonadeo/e-uscito-joypad/discussions/36#discussioncomment-3287126_

**Comment by pdonadeo** [comment]
Ho notato. @MarcoJul puoi occupartene tu?

**Comment by MarcoJul** [comment]
Roger Roger👍

**Comment by agofa** [comment]
> Roger Roger👍

La versione online sembra non avere più il problema

**Comment by agofa** [comment]
> > Roger Roger👍
> 
> La versione online sembra non avere più il problema 

Come non detto
Ci sono ancora problemi vari in varie situazioni 


![Screenshot_20220731-164543_Firefox.jpg](https://user-images.githubusercontent.com/19308040/182031827-6d2234ff-983a-40bc-91bc-a9a62d59a3cc.jpg)

**Comment by agofa** [comment]
Stessa situazione con duckduck

![Screenshot_20220731-165057_DuckDuckGo.jpg](https://user-images.githubusercontent.com/19308040/182032040-c04f14fe-9e55-4181-a238-bd6fb659f60b.jpg)

**Comment by agofa** [comment]
Ho fatto altri test e con FF Android la tastiera sistematicamente copre tutta la barra di ricerca.
Tanto dovevo

**Comment by pdonadeo** [comment]
@MarcoJul fammi un commento qui sotto altrimenti non posso assegnarti la issue.

**Comment by MarcoJul** [comment]
Eccomi!

**Comment by agofa** [comment]
@MarcoJul e @pdonadeo questo mi sembra ancora da sistemare

**Comment by pdonadeo** [comment]
Ma difatti nessuno ha messo mano a questa issue 😅

**Comment by agofa** [comment]
Fate con comodo eh? :-)

(si scherza)

**Comment by pdonadeo** [comment]
Più in generale il sito è "tutto rotto" su Firefox Mobile, almeno su Android ma immagino anche su iOS. Onestamente lo ritengo poco prioritario: Firefox Mobile ha un market share stimato dello 0.6% ed in pratica lo uso solo io.

Lo sistemeremo ma davvero "chissene".

**Comment by agofa** [comment]
Cavoli
Io e te siamo lo 0.66%?

(comunque sono d'accordo)

**Comment by pdonadeo** [comment]
@agofa questo è chiuso per te?

**Comment by agofa** [comment]
Yep. Si può chiudere

**Comment by agofa** [comment]
> @agofa questo è chiuso per te?

Yep. Si può chiudere
