### ISSUE TITLE
Rendering del file statico molto diverso dal rendering React: il layout ha un "flash" fastidioso

### ISSUE THREAD

**Issue by agofa** [pdonadeo/e-uscito-joypad#41]
Al primo accesso, qualsiasi browser desktop, la pagina si presenta così per 1 secondo circa
Anche con un refresh.
Ho fatto una ventina di refresh in modo compulsivo e si è proprio bloccata su questa vista e quindi ho potuto catturarla

![immagine](https://user-images.githubusercontent.com/19308040/182103353-f0455de3-3830-4226-84ac-79562116915b.png)

**Comment by pdonadeo** [comment]
@agofa però questo non mi torna proprio: sto provando anche io da due browser desktop diversi (Firefox e Chrome) e funziona perfettamente. Sei a casa o in ufficio? Non è che c'è qualche proxy aziendale strano?

**Comment by agofa** [comment]
Sono in ufficio ma non ci sono proxy né altro, forse fastweb stamattina ha le paturnie
Spe che provo con connessione cellulino ... appunto, cancella pure, problemi fastwebiani direi

**Comment by pdonadeo** [comment]
Ok, comunque grazie per la segnalazione.

**Comment by agofa** [comment]
Ho riprovato da casa, con il notebook di lavoro e il notebook della moglie
Il problema si è ripresentato, ad ogni accesso la pagina di cui sopra rimane visibile per un paio di secondi
Per esempio proprio ora, con Chrome, ho fatto un refresh, pagina rimasta visibile per un po' e poi è apparsa la home

La mia diagnosi è un esaustivo e definitivo BOH?

**Comment by pdonadeo** [comment]
@agofa scusa ho prestato davvero attenzione a questa cosa solo ora: ma quella è la vecchia visualizzazione, o sbaglio? Cioè è la vecchia "versione" del sito prima che andassimo on line con la nuova versione, corretto? E rimane lì per poco e poi cambia in quella nuova o rimane fissa la vecchia?

**Comment by agofa** [comment]
> E rimane lì per poco e poi cambia in quella nuova o rimane fissa la vecchia?

Per poco, a volte solo una specie di flash
Poi appare la home nuova

Se sia la vecchia, boh? echisiricorda? :-)

**Comment by pdonadeo** [comment]
> Per poco, a volte solo una specie di flash

Allora ho capito: è un problema che deriva da… ok, vorrei evitare un pippone tecnico. So esattamente cos'è e ho provato a risolverlo senza successo.

Tengo aperta questa issue perché effettivamente è fastidioso e prima o poi va sistemato.

**Comment by pdonadeo** [comment]
@agofa fai un salto su [staging](https://staging.euscitojoypad.it/) per vedere se così ti piace. Ho cercato di togliere tutto il "flashing" che potevo: non è perfetto ma toglierlo del tutto significa riscrivere tutto il sito con altre tecnologie.

**Comment by agofa** [comment]
Direi PERFETTO
Io passerei in prod questa modifica, mi sembra vada più che bene

**Comment by pdonadeo** [comment]
> Io passerei in prod questa modifica, mi sembra vada più che bene

Fatto, è in produzione.
