### ISSUE TITLE
Scrollbar orizzontale presente inutilmente

### ISSUE THREAD

**Issue by paolozanchi** [pdonadeo/e-uscito-joypad#46]
Il sito mostra una scrollbar orizzontale inutilmente, anche quando il browser è a schermo intero (testato su Chrome 104.0.5112.102 e Firefox 104.0.1).

![image](https://user-images.githubusercontent.com/2668575/188430318-44a4a282-cdcd-4927-971c-5f59ee63559b.png)

Non ho esperienza con React però il problema scompare applicando la regola `max-width:100%;` al tag `<body>` ([soluzione presa da qua se può servire](https://stackoverflow.com/questions/23367345/100vw-causing-horizontal-overflow-but-only-if-more-than-one))

**Comment by pdonadeo** [comment]
Non riesco a riprodurlo con Firefox (Linux) ma con Chrome decisamente sì.

Grazie @paolozanchi cerchiamo di sistemarlo il prima possibile.

**Comment by agofa** [comment]
Confermo con Chrome e Edge, Windows
Il problema non c'è con Firefox

**Comment by agofa** [comment]
Boh? Ora è apparsa anche con FF e Windows
Ieri non c'era, giuro!

![immagine](https://user-images.githubusercontent.com/19308040/188910353-2ea5ae4b-5db4-4d01-aaf6-b18a5677157d.png)

**Comment by pdonadeo** [comment]
Purtroppo ho ricominciato a lavorare, se ne parla nel fine settimana, sempre che @MarcoJul non ci metta una pezza prima.

**Comment by agofa** [comment]
Allora, fammi capire: cosa NON ti paghiamo a fare?

(vado vado)

**Comment by pdonadeo** [comment]
@MarcoJul fammi un commento qui sotto altrimenti non posso assegnarti la issue.

**Comment by MarcoJul** [comment]
Commento!

**Comment by pdonadeo** [comment]
@paolozanchi questo lo possiamo chiudere?
