### ISSUE TITLE
Link diretto ad una ricerca

### ISSUE THREAD

**Issue by daitangio** [pdonadeo/e-uscito-joypad#54]
Ciao, innanzitutto complimenti per il sito: gradevole c con tecnologie all'avanguardia (conosco un po' tutto quello citato).
Vorrei includere qualche link del sito in dei mie aritcoli però non ho capito se  si può fare e come.
Porteste aggiungere un link "share" / "embed" per creare un link diretto ad una ricerca+ tab specifico di una puntata?

**Comment by pdonadeo** [comment]
Ciao Giovanni! Ma sai che questa è proprio una bella idea? Come avrai notato in questo momento non c'è nessun "router" lato client e quindi qualsiasi link è inutile, porta sempre alla "home page".

Certamente è una proposta utile ma la mia domanda è: perché scrivi _"Porteste aggiungere"_? Fallo tu, se ti va: fai fork e manda pull request.

Questo è un posto dove uno da un dito ed il progetto si mangia lui, la moglie, i figli e la casa :joy: 

Seriamente: se ti va contribuisci altrimenti questa per me rimane una cosa da fare.

**Comment by pdonadeo** [comment]
@daitangio mi rendo conto che è passato un anno ma il tempo libero è quello che è.

Prova qui: https://staging.euscitojoypad.it/se-ne-parla-qui/4/Death%20Stranding

Per accedere: `joypad`/`corrisaltaspara`.
