### ISSUE TITLE
Nella scheda dell'episodio invertire descrizione e recensioni

### ISSUE THREAD

**Issue by pdonadeo** [pdonadeo/e-uscito-joypad#55]
Richiesta da @zamale: invertire le schede "descrizione" e "recensioni".

![immagine](https://user-images.githubusercontent.com/242049/194006133-24d5ee2a-921f-4c4a-8ffb-d3332f5fb80f.png)

**Comment by agofa** [comment]
@MarcoJul forse questa è facile

**Comment by MarcoJul** [comment]
useEffect(() => {
      const groupsArr = [recensioni, consigli, chiacchiere];
      const firstActive = groupsArr.findIndex((group) => group.length !== 0);
      if (firstActive === -1) setSection("descrizione");
      if (firstActive === 0) setSection("recensioni");
      if (firstActive === 1) setSection("consigli");
      if (firstActive === 2) setSection("chiacchiere");
   }, [recensioni, consigli, chiacchiere]);

Altro che facile! Guarda che Quesito della Susi che devo cancellare!😅 
E' facile cancellarlo ma per il mio cervello la versione precedente è stata una sfida🤭

Comunque stasera mando tutto in PR, insieme a un bug fix di cui non mi sono accorto su quella precedente🖖

**Comment by pdonadeo** [comment]
Chiusa da PR #65
