### ISSUE TITLE
Box "ORDINA PER" è un layer al di sotto della lista episodi

### ISSUE THREAD

**Issue by Mascalian** [pdonadeo/e-uscito-joypad#57]
![image](https://user-images.githubusercontent.com/104673456/194294164-54449f33-4ea4-47e2-89cb-d0deea56e664.png)

Come da immagini, se si clicka sul pulsante per aprire l'ordinamento, il box è sotto la lista degli episodi.
#chrome #pc

**Comment by pdonadeo** [comment]
@MarcoJul come sopra. Scusa se ti taggo ma altrimenti non posso assegnarti il bug.

**Comment by agofa** [comment]
Ah su cellucoso non c'è il bug, ho provato con un paio di browser

**Comment by Mascalian** [comment]
Vero.
Perché in quel caso il layer torna solidale con la barra di ricerca.

Di contro, però, la larghezza della colonna unica eccede di poco la larghezza del device...
![image](https://user-images.githubusercontent.com/104673456/194724392-c8f74e94-8af3-47df-becd-3981c98c6ea3.png)

... e la scritta "Gli ultimi 8 episodi" si sovrappone all'header (a seconda della larghezza del device).
![image](https://user-images.githubusercontent.com/104673456/194724308-5896a7ba-da48-4fd8-b375-86a26b24164d.png)

(per chi non sapesse, si può agilmente mimare la visione su smartphone semplicemente rimpicciolendo la finestra del browser: sotto una certa dimensione, il browser rende la pagina come se fosse su un device piccolo)

**Comment by MarcoJul** [comment]
Vi spoilero il problema, semplicemente.. abbiamo sviluppato mobile-first e prima del live non ho avuto il tempo materiale per adattarlo su desktop😅

"stiamo lavorando per voi"

per quanto riguarda il controllo responsive, il resizing della finestra browser non è il massimo dell'affidabilita, già non lo è molto l'inspect di chrome.. per controlli più precisi (oltre a usare cellulari fisici su staging) sono browser come Blisk o simili😉

**Comment by MarcoJul** [comment]
Rispondo qua per tutte le issue riguardo ORDINA PER.

Ho riscritto il tutto per:

- modificare la tendina di ordinamente se su desktop (come da design originale mai integrato); 
- aggiungere il pointer alle varie voci (non ho messo un'hover perché diventa tutto animato eccessivamente);
- aggiungere un'icona che mostri lo stato attuale dell'ordinamento;
- animazioni di attivazione/disattivazione;
- varie ed eventuali;

@pdonadeo per queste modifiche ho creato un Branch a parte, ISSUE_Desktop-sorting, preferisci fare tu l'acchiappo o faccio la PR sulla tua repository?

di conseguenza poi sguinzagliamo @agofa per il testing😁

**Comment by pdonadeo** [comment]
@MarcoJul fai pure la request, facciamo quelli che la sanno lunga 😂

**Comment by MarcoJul** [comment]
Fatta la PR, ormai siamo bimbi grandi dai😆

**Comment by agofa** [comment]
Tendina ordinamento OK, provato con FF e edge

**Comment by agofa** [comment]
Una nota, il funzionamento del widget ordinamento è corretto anche dopo una ricerca, cioè con a video il risultato ricerca, solo che non ho capito in questo caso cosa ordina, quale sia la regola

**Comment by pdonadeo** [comment]
> Una nota, il funzionamento del widget ordinamento è corretto anche dopo una ricerca, cioè con a video il risultato ricerca, solo che non ho capito in questo caso cosa ordina, quale sia la regola

Eh, bella domanda 😅

**Comment by MarcoJul** [comment]
Ehi che comportamento strano! Controllo quali sono i criteri e su cosa ordina, se faccio una ricerca e ordino i contenuti li mescola abbastanza a caso🤔

**Comment by pdonadeo** [comment]
Chiusa da #62
