### ISSUE TITLE
Box "ORDINA PER" non appare come link

### ISSUE THREAD

**Issue by Mascalian** [pdonadeo/e-uscito-joypad#58]
Banalmente, è un < p > ma non ha i CSS "cursor: pointer", o meglio ancora le pseudo classi simil collegamenti

**Comment by pdonadeo** [comment]
@MarcoJul ti torna? Io non ho controllato ma a occhio direi che confermiamo.

**Comment by pdonadeo** [comment]
Chiuso da #62
