### ISSUE TITLE
Ordinamento degli episodi trovati con ricerca non intuitivo

### ISSUE THREAD

**Issue by glenacota** [pdonadeo/e-uscito-joypad#64]
Gli episodi trovati usando la funzione di ricerca sono visualizzati per similarity crescente e priorita' (hard-coded) inversa, quindi non necessariamente in ordine cronologico (che va benissimo ;) ). Tuttavia, se a questo punto clicco su "ORDINA PER / Piu' recenti | Meno recenti", mi aspetterei un ordinamento cronologico, che invece non viene applicato.

Per esempio, 
1. cerco il gioco "monkey island"
2. i primi episodi ottenuti sono 55, 26, 47, 12 ...
3. ordino per "Meno recenti" e ottengo episodi 52, 54, 50, 12, ...
4. ordino per "Piu' recenti" e ottengo episodi 55, 26, 47, 12, ... (l'ordinamento di default)

Trovo questo comportanto un po' controintuitivo. Che ne pensate di fare in modo che "ORDINA PER" sovrascrivi i criteri di ordinamento di default?

**Comment by pdonadeo** [comment]
La lista degli episodi in questo momento è ambivalente:
 1. se non si cerca nulla è la lista degli ultimi episodi
 2. se si ricerca, è il risultato della ricerca

Forse potremmo pensare che in presenza della ricerca si disattivi del tutto la funzionalità di ordinamento perché effettivamente così non ha senso.

@MarcoJul che ne pensi? È una modifica facile e se sei d'accordo col disattivare la tendina mentre è in atto una ricerca lo posso fare io.

**Comment by MarcoJul** [comment]
Non c'è problema ci posso pensare io, organizzo una sparizione "controllata" in modo che siamo al sicuro per tutte le situazioni.

Detta così sta frase è pericolosa, se non avrete più mie notizie sapete che sono stato terribilmente frainteso😅

**Comment by pdonadeo** [comment]
È già on line su [staging](https://staging.euscitojoypad.it/).

@MarcoJul @glenacota fate sapere se così è meglio.

**Comment by MarcoJul** [comment]
A livello di funzionalità ok, metterei magari che l'icona della ricerca viene sostituita da una "X" che ha la funzione appunto di nascondere l'ordinamento e, al click, di svuotare il campo di ricerca in corso.

**Comment by pdonadeo** [comment]
> metterei magari che l'icona della ricerca viene sostituita da una "X" che ha la funzione appunto di nascondere l'ordinamento e, al click, di svuotare il campo di ricerca in corso.

Ah, carino! Oggi pomeriggio lo faccio.

**Comment by pdonadeo** [comment]
@MarcoJul ho aggiornato [staging](https://staging.euscitojoypad.it/), ti piace?

**Comment by agofa** [comment]
> @MarcoJul ho aggiornato [staging](https://staging.euscitojoypad.it/), ti piace?

A me sì
