### ISSUE TITLE
Home page cellulino

### ISSUE THREAD

**Issue by agofa** [pdonadeo/e-uscito-joypad#84]
Questione moooolto moooolto secondaria, inutile assai ma la documento per eventuali sistemazioni
L'attuale versione ha un piccolo piccolo problema in home page, i widget Instagram e Discord si mischiano un pochino con la label "ecco gli ultimi 8 episodi"
Effetto più o meno evidente a seconda del browser e del cellulino
La foto qui sotto è presa da un vecchio (sigh) Motorola X4 e DuckDuckGo

![immagine](https://user-images.githubusercontent.com/19308040/230869325-54491bc7-c987-4cfd-a161-a21cf6cf67c7.png)

**Comment by agofa** [comment]
Su iOS e vari browser il problema non c'è.
Su Android non è sistematico.

Che dire?
Scriverò le risoluzioni video appena potrò

**Comment by pdonadeo** [comment]
Il problema è che questo è più che altro un bug di Firefox mobile e browser derivati. Ad esempio sul mio Android il layout del sito è completamente "scassato" con Firefox mentre con Chrome è perfetto.

Un sito a casaccio di quelli che danno le statistiche di market share pone Firefox allo 0.61%

![image](https://user-images.githubusercontent.com/242049/233807387-bf5144b9-f3af-4503-bf26-cb6f81754cb5.png)

Non so quanto sia affidabile ma è verosimile. Non so se lo aggiusteremo mai, si rischia di introdurre modifiche che rompono il layout con Chrome e Safari e onestamente secondo me il gioco no vale la candela.
