### ISSUE TITLE
Home page tablet

### ISSUE THREAD

**Issue by agofa** [pdonadeo/e-uscito-joypad#85]
Ogg mi ha preso così
Tablet Lenovo 10 pollicioni

La Home page è un po' spostata
Vedi immagine qui sotto

![HomePage_tablet](https://user-images.githubusercontent.com/19308040/230869648-11b6da61-7cc9-4c8a-9879-24873ad5c3ce.jpeg)

**Comment by agofa** [comment]
Ovviamente priorità -145.567,56

**Comment by pdonadeo** [comment]
Chiuso con la versione 31
